// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lvcgffawmzjeeaiausme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx2Y2dmZmF3bXpqZWVhaWF1c21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NzU1NTIsImV4cCI6MjA1ODE1MTU1Mn0.gqg8hyZQg76eKETYZzKklXxwyFdUW4uu619q-yS-UMo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);